### ISSUE TITLE
Green notification bar

### ISSUE THREAD

**Issue by trey8611** [jekylldream/duplicate-plugin#5]
What is this green bar?

![2018-04-12_22-59-19](https://user-images.githubusercontent.com/1909875/38714659-467eb4cc-3ea5-11e8-97da-5167fb42abeb.png)

**Comment by Spellhammer** [comment]
That was an admin notification I put in to show me debug messages while coding it. I'll remove it in the next commit.

**Comment by Spellhammer** [comment]
Fixed.
